rostools/git4cats

sessions/prs.md
This PR adds a sentence on wny PRs are called PRs. I stumbled across this when reading some tidyverse documentation and thought it was nice to include here as well.
=> docs: add why prs are called prs

preamble/syllabus.qmd
=> docs: :memo: add learner assumptions

.vscode/extentions.json, .vscode/settings.json
Add settings and extensions for vscode.  
Closes #19
=> chore(devops): 🧑‍💻 add vscode settings and extensions

.github/CODEOWNERS
=> chore(devops): :technologist: add CODEOWNERS to auto add reviewers

.github/workflows/build-website.yml
Adding this so that we use a central workflow rather than each repo using it's own.
=> ci(devops): :construction_worker: use the organizations website builder workflow

_quarto.yml
If you have an ORCID, please add it :)
=> chore: :wrench: add @signekb to author list in Quarto config file

_quarto.yml, includes/contribute.html
=> chore: :globe_with_meridians: fix URLs to point to correct locations

index.qmd
I mostly copied and pasted over from the other courses. It isn't finished, since we need the Challenge and Need section filled out eventually.
This PR needs a bit of a review.
=> docs: :memo: update landing page of website

.gitignore
We don't want to track these in Git.
=> chore(devops): :see_no_evil: ignore the built website files

sessions/lesson.qmd
Now that the last R code chunk is removed, we can render the website without that dependency.
Closes #39
=> chore: :fire: remove last R code chunk so Quarto doesn't need to use R

preamble/pre-course.qmd, preamble/syllabus.qmd
Sicne we aren't going to be using R, I removed all text about it.
Also closes #39
=> docs(sessions): :memo: remove all references to R in current files

preamble/syllabus.qmd
Closes #29 
This PR needs a quick review. 
Focus on CHANGES.
=> docs: :memo: add learner assumption about Git and GitHub experience

.vscode/settings.json
It seems like the other scopes match folders in this repo, so I thought it made sense to add these two as well. 
This PR needs a quick review. 
Focus on CHANGES.
=> chore(devops): :sparkles: add preamble and slides to scopes

preamble/schedule.qmd
I have added the schedule based on the discussions in #2 to the schedule. I thought that it would make things a bit clearer to see the course/sessions in the schedule, but the exact sessions/schedule is still up for debate. What do you think? 
Closes #6
This PR needs an in-depth review.
=> docs(preamble): 📝 update sessions in schedule

preamble/schedule.qmd
This PR fixes a typo in the links to the group project. I had written "session" instead of "sessions". Sorry about that.
=> fix: :pencil2: session -> sessions

preamble/syllabus.qmd
This PR completes some minor text edits in the `syllabus.qmd`. 
Mainly, I have tried to remove words and sentences that are (/that I deem) unnecessary to try to keep things a bit simpler and more to the point :) 
I also fixed a layout issue with the nested lists. 
Closes #14 (this issue is the reason why I started going through this file, but it was almost filled out already)
This PR needs an in-depth review.
=> docs: 📝 update text by simplifying a bit

README.md
These changes are to align the title and subtitle in the `README` with what we have agreed on in #40 and implemented in #57 .
While I was at it, I added a licence badge as well.
=> docs: 📝 update title and add license badge

sessions/lesson.qmd
To help align the structure of this section across sessions. 
=> docs: :memo: add learning objectives section to lesson template

_quarto.yml, appendix/social.qmd, includes/_wip.qmd, index.qmd, preamble/pre-course.qmd, preamble/schedule.qmd, preamble/syllabus.qmd, sessions/_old/branching.qmd, sessions/_old/commits.qmd, sessions/_old/git.qmd, sessions/_old/index.qmd, sessions/_old/introduction.qmd, sessions/_old/issues.qmd, sessions/_old/prs.qmd, sessions/introduction.qmd, sessions/lesson.qmd, sessions/what-next.qmd
... Instead of being in each individual section.
As you did in `seedcase-sprout`. If you don't like it, you can just close this PR again.
=> refactor: :art: centralise wip callout to be in body-header

preamble/pre-course.qmd
=> docs: :memo: add create GitHub account to precourse tasks

sessions/introduction.qmd
These changes add the big picture section of the intro session.
Closes #61
This PR needs an in-depth review.
=> docs(sessions): :memo: add text for big picture
